### PR TITLE
feature/travis_bench

### PR DESCRIPTION
**Pull request by th0br0**
* 	collections crate was renamed to alloc upstream
*       Make TravisCI run benchmarks as well.

### CODE REVIEW

**Comment by th0br0** [comment]
@iotaculus r+

**Comment by iotaculus** [comment]
:pushpin: Commit 341ced9 has been approved by `th0br0`

**Comment by iotaculus** [comment]
:hourglass: Testing commit 341ced931c2a00bc8fb85f97f206940edf8a3fc5 with merge 8b7ed855854e852821627e07f7b4c3d09f758a43...

**Comment by iotaculus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/iotaledger/iota.rs/builds/248157612?utm_source=github_status&utm_medium=notification)
Approved by: th0br0
Pushing 8b7ed855854e852821627e07f7b4c3d09f758a43 to master...

**Comment by th0br0** [comment]
@iotaculus r+

**Comment by iotaculus** [comment]
:pushpin: Commit 341ced9 has been approved by `th0br0`

**Comment by iotaculus** [comment]
:hourglass: Testing commit 341ced931c2a00bc8fb85f97f206940edf8a3fc5 with merge 707457ee9bd4b2219e3b7d4b3dcdd2aceb0bc018...

**Comment by th0br0** [comment]
@iotaculus r+

**Pull request merged**
